name: CI
'on':
  - push
jobs:
  Tests:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        node-version:
          - '12'
          - '14'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - run: npm i
      - run: npm cover
        env:
          CI: 'true'
      - run: npm run cover
        env:
          CI: 'true'
  Release:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        node-version:
          - '12'
        os:
          - ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - run: npx semantic-release
        env:
          CI: 'true'
